/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    @org.testng.annotations.Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
